### ISSUE TITLE
Reorder arguments in decorator methods

### ISSUE THREAD

**Issue by tomfitzhenry** [javaslang/javaslang-circuitbreaker#10]
I have a few decorator methods that have various behaviours including rate limiting, timing, and of course, circuit breaking! I apply these in a chain, as per the decorator pattern.

`CircuitBreaker.decorateSupplier` has a type signature `Supplier<T> decorateSupplier(Supplier<T> supplier, CircuitBreaker circuitBreaker)`, so chaining multiple decorator methods looks like:

```
RateLimiter.decorateSupplier(rateLimitConfig,
    CircuitBreaker.decorateSupplier(
        Stopwatch.decorateSupplier(stopwatchConfig,
            mySupplier()), circuitBreaker));
```

Notice that the CircuitBreaker instance is far from where it is applied in the chain, and looks out of place.

If `CircuitBreaker.decorateSupplier` had a type signature of `Supplier<T> decorateSupplier(CircuitBreaker circuitBreaker, Supplier<T> supplier)`, then the same code would look like:

```
RateLimiter.decorateSupplier(rateLimitConfig,
    CircuitBreaker.decorateSupplier(circuitBreaker
        Stopwatch.decorateSupplier(stopwatchConfig,
            mySupplier()));
```

Now it's easier to associate the `CircuitBreaker` instance with the call to `CircuitBreaker.decorateSupplier`

**Comment by RobWin** [comment]
Hi,
indeed. Looks much better that way.

If you use the library, I would love to get your GitHub Star.

**Comment by RobWin** [comment]
@tomfitzhenry Did you publish your RateLimiter somewhere?

**Comment by storozhukBM** [comment]
@RobWin @tomfitzhenry I've request limits implementation inspired by your library [here ](https://github.com/storozhukBM/requestlimit). But it is on early stages. 
There is:
* Contracts and interfaces similar to your javaslang-circuitbreaker library
* Stupid simple implementation of request limiter
* 100% tests coverage

To make it fully usable I plan to add:
* Add full javadoc
* Write README
* Create example directory
* Write JMH benchmark for implementation of request limiter

I know that current implementation of request limiter is too straightforward and possibly can have some performance problems but I decided to go with it at first. And after JMH benchmark available I will be able rewrite something based on ring buffer of timestamps.

**Comment by RobWin** [comment]
I added the new signatures and deprecated the old signatures in the upcoming v0.7.0

**Comment by RobWin** [comment]
Would you like to contribute such a feature to javaslang-circuitbreaker?

**Comment by storozhukBM** [comment]
@tomfitzhenry Yep. I've already look through this and several other implementations. And have overall understanding of pros and cons of different algorithms. But I don't sure that such feature should be added to javaslang-circuitbreaker because it is already concise and beautiful single responsibility library. 
On my current project I've created abstraction called `Gateway`. Every API call is proxied through this `Gateway` and it is responsible for invocation of circuitBreaker, requestLimit and/or metrics.

Like that:
```java
public class GatewayInterceptor implements MethodInterceptor {
    private final Logger log = LoggerFactory.getLogger(GatewayInterceptor.class);
    private final ApiType apiType;
    private final Try.CheckedFunction<MethodInvocation, Object> gatewayInvoke;

    public GatewayInterceptor(ApiType apiType, RequestLimit requestLimit, CircuitBreaker circuitBreaker) {
        this.apiType = apiType;
        Try.CheckedFunction<MethodInvocation, Object> circuitBreakerInvoke = CircuitBreaker.decorateCheckedFunction(
            MethodInvocation::proceed,
            circuitBreaker
        );
        Try.CheckedFunction<MethodInvocation, Object> requestLimitInvoke = RequestLimit.decorateCheckedFunction(
            circuitBreakerInvoke,
            requestLimit
        );
        gatewayInvoke = requestLimitInvoke;
    }

    @Override public Object invoke(final MethodInvocation invocation) throws Throwable {
        Object result = Try.success(invocation)
            .mapTry(gatewayInvoke)
            .onFailure(throwable -> log.error("Error in invocation of {} API: {}", apiType, throwable.getMessage()))
            .get();
        return result;
    }
}
```
@tomfitzhenry What do you think about it? Should we javaslang-circuitbreaker or create additional library that will compose  few other libraries?

**Comment by RobWin** [comment]
Let's move the discussion to #12. Could you copy your comment into this issue? 
Besides that, @tomfitzhenry is not the maintainer, but it's me :)

If a RateLimiter implementation is lightweight in the sense that we don't need any other 3rd party libraries, we can add it to javaslang-circuitbreaker. A RateLimiter is also some sort of CircuitBreaker. A RateLimiter can forbid further calls, if a rate limit has exceeded.

The retry functionality is also not related to CircuitBreakers.
