### ISSUE TITLE
try tests: how come the sleep time is zero?

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang-circuitbreaker#17]
i'm trying to improve the retry tests but it seems for them the waiting time between retries is zero although we call "ofDefaults" which should mean a sleep time of 500ms. I can't find the piece of magic which overrides this sleep time for the tests?

**Comment by RobWin** [comment]
Hi,

thx for contributing. It would be nice if you would like to improve the retry functionality. Maybe by introducing a delay which back offs exponentially instead of a fixed delay between delays.

**Comment by RobWin** [comment]
I have a look at the tests.

**Comment by emmanueltouzery** [comment]
yes!! I exactly want to add a setBackoffFunction(Function<Duration,Duration>) :-)

**Comment by emmanueltouzery** [comment]
and as a first step I want to improve the tests so it's possible to asset how much time was slept. I'm almost done on that but confused because the tests don't sleep at all :-) sleep time = 0.

**Comment by RobWin** [comment]
Might be a bug

**Comment by emmanueltouzery** [comment]
FYI my approach is to make it possible to use another function instead of Thread.sleep, that function has a counter (and doesn't sleep) and that way we can assert how long the sleep last.

Some bits:

    private static Try.CheckedConsumer<Long> sleepFunction = Thread::sleep;

    RetryContext.testsSetSleepFunction(sleep -> sleptTime += sleep);

    assertThat(sleptTime).isEqualTo(RetryContext.DEFAULT_WAIT_DURATION);

In other words the goal before that would be that Thread.sleep is called with the right waiting time. I was looking at this before, it's called with 0. Tried to track down where it's modified for tests and failed. 

 In the constructor of RetryContext this helps =>

    this.waitDuration = 500; //waitDuration.getSeconds() * 1000;

 But fixing the caller of RetryContext does NOT help (build()). In addition modifying the tests to build the context like that:

    Retry retryContext = Retry.custom().waitDuration(java.time.Duration.ofMillis(500)).build();

also doesn't help. It's like something is mocked in test mode or something...

**Comment by emmanueltouzery** [comment]
right. now that i sat down again and looked a it again and saw it immediately...

            this.waitDuration = waitDuration.getSeconds() * 1000;

set a sleep time of 500ms (the default!!!) and getSeconds() will return 0, and you don't sleep at all, it only works at the second resolution. I'll fix that through my PR as well, coming soon!
